version: "3.9"

networks:
  asn-net:
    external: true

services:
  backend:
    image: bitnoize/asn:latest
    container_name: asn-backend
    build:
      context: .
    init: true
    environment:
      - UID=${ASN_UID:-8193}
      - GID=${ASN_GID:-8193}
    ports:
      - 127.0.0.1:5555:5555
    networks:
      - asn-net
    restart: unless-stopped
    deploy:
      mode: global

